### ISSUE TITLE
能否增加支持的网站？

### ISSUE THREAD

**Issue by majiayeah** [Xmader/Revolter#1]
你好，此软件很有用，感谢！

但目前好像只能支持中文维基，软件主页面上那个网址和端口都是灰色不可更改状态。

请问能否增加支持其他网站？让网址可以填写。毕竟被SNI RST的网站还有很多。

谢谢！

**Comment by Xmader** [comment]
您好，在最新的 `v1.1.0` 版本中添加了对修改远程域名和远程端口的支持，请尽情享用吧。
